[package]
name = "runjs"
version = "0.1.0"
edition = "2024"

[dependencies]
deno_ast = "0.48.0"
deno_core = "0.350.0"
deno_error = "0.6.1"
reqwest = "0.12.18"
tokio = { version = "1.45.1", features = ["full"] }
